openapi: 3.0.0

info:
    version: 1.0.0
    title: Web of Web Trust Backend
    description:
        The API for the backend for the web of web trust browser extension
    contact:
        name: 'Cobalt'
        url: 'https://cobalt.rocks/content/contact/'
        email: 'c0balt@disroot.org'
    license:
        name: 'AGPL-3-only'
        url: 'https://<Insert License Link>'

security: []

paths:
    /healthcheck:
        get:
            description: Returns 200 when app is running okay
            responses:
                '200':
                    description: Successful response
    /api/v1/spec.yml:
        get:
            description: Get the OpenAPI v3 spec document for the API
            responses:
                '200':
                    description: Successful
                '404':
                    description: Server doesn't support spec serving
    /api/v1/domains/